### ISSUE TITLE
there is no file named "coxgraph_client.launch"

### ISSUE THREAD

**Issue by PuYuuu** [zju3dv/coxgraph#1]
Hi, thanks your for this amazing working!

When i run "roslaunch coxgraph run_experiment_euroc.launch", shell warned that "there is no such file or directory:coxgraph_client.launch" called from "run_experiment_euroc.launch" line 22.

And i do can't find this file in the repository.

**Comment by HongLouyemeng** [comment]
> Hi, thanks your for this amazing working!
> 
> When i run "roslaunch coxgraph run_experiment_euroc.launch", shell warned that "there is no such file or directory:coxgraph_client.launch" called from "run_experiment_euroc.launch" line 22.
> 
> And i do can't find this file in the repository.

me too!

**Comment by yxianzhe** [comment]
[https://github.com/zju3dv/coxgraph/issues/1#issue-1077558333](url)me too!

**Comment by yxianzhe** [comment]
> 

I also had this mistake..

**Comment by HongLouyemeng** [comment]
> > 
> 
> I also had this mistake..

Does the code work correctly?

**Comment by HongLouyemeng** [comment]
> Hi, thanks your for this amazing working!
> 
> When i run "roslaunch coxgraph run_experiment_euroc.launch", shell warned that "there is no such file or directory:coxgraph_client.launch" called from "run_experiment_euroc.launch" line 22.
> 
> And i do can't find this file in the repository.

https://github.com/mfkiwl/coxgraph

**Comment by chen12345678910** [comment]
> > 嗨，感谢您的出色工作！ 
> > 当我运行“roslaunch coxgraph run_experiment_euroc.launch”时，shell 警告说“没有这样的文件或目录：coxgraph_client.launch”从“run_experiment_euroc.launch”第 22 行调用。 
> > 而且我确实在存储库中找不到这个文件。
> 
> [https://github.com/mfkiwl/coxgraph ](https://github.com/mfkiwl/coxgraph)

Did you run it successfully?

**Comment by HongLouyemeng** [comment]
> 

No,This code doesn't work

**Comment by XiliangLi** [comment]
> > 
> 
> No,This code doesn't work
Since these codes are missing some files, they are not working properly at the moment. I will upload the latest code as soon as possible, thank you for your interest in this work

**Comment by XiliangLi** [comment]
> > 
> 
> No,This code doesn't work

Since these codes are missing some files, they are not working properly at the moment. I will upload the latest code as soon as possible, thank you for your interest in this work
