### ISSUE TITLE
Please check your code and run it on the new machine!

### ISSUE THREAD

**Issue by HongLouyemeng** [zju3dv/coxgraph#5]
[ WARN] [1646903072.967187474]: **Received submap with empty trajectory. Skipping submap**.
I0310 01:04:54.919852 11237 tsdf_esdf_submap.h:55] **EsdfSubmap 2 is being deleted.**
I0310 01:04:54.920315 11237 tsdf_submap.h:45] **TsdfSubmap 2 is being deleted**

**Comment by HongLouyemeng** [comment]
no previous pose graph

**Comment by HongLouyemeng** [comment]
roslaunch parent running, waiting for process exit

**Comment by Ethereal-Tian** [comment]
Can you describe the question in detail? We have updated our code. Maybe you can have a try.
