### ISSUE TITLE
[ERROR] [1651806197.365026004]: Error writing: Error opening file: /workspaces/voxgraph_melodic_ws/eval/tf_record_2022-05-06-11-03-17.bag.active

### ISSUE THREAD

**Issue by chen12345678910** [zju3dv/coxgraph#6]
I ran into the following problems:
[ERROR] [1651806197.365026004]: Error writing: Error opening file: /workspaces/voxgraph_melodic_ws/eval/tf_record_2022-05-06-11-03-17.bag.active

**Comment by XiliangLi** [comment]
> 

This error doesn't influence the result , or you can modify the path to yours if you don't want to get this error
