### ISSUE TITLE
Given package 'vins_client_server' is not in the workspace

### ISSUE THREAD

**Issue by Zhangxiurui520** [zju3dv/coxgraph#7]
Hi LXY!
how can i get the package 'vins_client_server' , i i didn't find it

**Comment by XiliangLi** [comment]
This package is in `coxgraph_ssh.rosinstall`, please see [here](https://github.com/zju3dv/coxgraph/blob/main/coxgraph_ssh.rosinstall#:~:text=git%3A%20%7Blocal%2Dname%3A%20vins_client_server%2C%20uri%3A%20%27git%40github.com%3ALXYYY/vins_client_server.git%27%2C%20version%3A%20%27develop%27%7D). If you could install this code following this [readme.md](https://github.com/zju3dv/coxgraph/blob/main/README.md) step by step, this package usually would be installed automatically. Please install this code again!

**Comment by Zhangxiurui520** [comment]
Thank you for your help sincerely!!

**Comment by Zhangxiurui520** [comment]
Thank you for your help Sincerely!
